unagi/blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path("posts/<int:pk>/", views.PostView.as_view(), name="post"),
]

unagi/unagi/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("dash_admin/", admin.site.urls), # rewrite the admin URL to avoid bots
    path("", include("blog.urls")),
]

if settings.DEBUG:
    urlpatterns += (path("__debug__/", include("debug_toolbar.urls")),)

unagi/blog/models.py
from django.contrib import admin
from django.db import models


class Post(models.Model):
    title = models.CharField("title", max_length=255)
    cover_image_url = models.URLField("cover image url", max_length=255, null=True, default=None, blank=True)
    created_at = models.DateTimeField("created at", auto_now_add=True)
    updated_at = models.DateTimeField("updated at", auto_now=True)
    posted_at = models.DateTimeField("posted at", null=True, default=None, blank=True)
    hidden_at = models.DateTimeField("hidden at", null=True, default=None, blank=True)
    content = models.TextField("content")

    @admin.display(
        boolean=True,
        ordering="posted_ad",
        description="Online?",
    )
    def is_online(self):
        return self.posted_at is not None and self.hidden_at is None

    def __str__(self):
        return self.title

unagi/blog/views.py
from django.views.generic import DetailView, ListView

from .models import Post


class IndexView(ListView):
    """Actually a PostListView, to show latest posts and allow to navigate through pages."""

    model = Post
    paginate_by = 3
    ordering = "-posted_at"
    template_name = "blog/index.html"
    
    def get_queryset(self):
        return super().get_queryset().filter(posted_at__isnull=False, hidden_at__isnull=True)
    
class PostView(DetailView):
    """View for displaying a single post."""
    
    model = Post
    template_name = "blog/post.html"
    
    def get_queryset(self):
        return super().get_queryset().filter(posted_at__isnull=False, hidden_at__isnull=True)

unagi/blog/templates/blog/index.html
{% extends "base.html" %}

{% block content %}
<div id="index-container" class="centered-flex-container">
    {% for post in post_list %}
        <a href="{% url "blog:post" post.id %}" class="flat-link">
            <div class="post-card">
                {% if post.cover_image_url %}
                    <div class="cover-image-container">
                        <img class="cover-image" src={{ post.cover_image_url }} alt="Cover image"/>
                    </div>
                {% endif %}
                <div class="writing-container">
                    <h3>{{ post.title }}</h3>
                    <p class="meta-info">Published on {{ post.posted_at }}</p>
                    <div class="post-overview">{{ post.content|safe|truncatechars_html:120 }}</div>
                </div>
            </div>
        </a>
    {% endfor %}

    <div>
        <span>
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}" class="flat-link"><</a>
            {% else %}
                <span class="disabled"><</span>
            {% endif %}

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="flat-link">></a>
            {% else %}
                <span class="disabled">></span>
            {% endif %}
        </span>
    </div>
</div>
{% endblock content %}

unagi/blog/templates/blog/post.html
{% extends "base.html" %}

{% block content %}
<div id="post-container" class="centered-flex-container">
    <a href="{% url "blog:index" %}" class="flat-link"><</a>
    <h1>{{ post.title }}</h1>
    <p class="meta-info">Published on {{ post.posted_at }}</p>
    {% if post.cover_image_url %}
        <img src={{ post.cover_image_url }}/>
    {% endif %}
    {{ post.content|safe }}
</div>
{% endblock content %}

unagi/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Unagi blog</title>
        <link rel="shortcut icon" type="image/svg" href="{% static 'favicon.svg' %}"/>
        <link rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="{% static 'blog/style.css' %}">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>

    <body>
    {% block header %}
    <header>
        <h1>Unagi blog</h1>
    </header>
    {% endblock header %}
    {% block content %}{% endblock content %}
    </body>
</html>